version: '3.8'

services:
  auth-db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
    volumes:
      - authdb_data:/data/db 

  service-db:
    image: mongo:6.0
    ports:
      - "27020:27017" # my service-db will be exposed on port 27020
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
    volumes:
      - servicedb_data:/data/db 

  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "16686:16686"  # Jaeger UI
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: true
  

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "4000:3000"

volumes:
  authdb_data:
  servicedb_data: